### ISSUE TITLE
default insert mode when open pantran

### ISSUE THREAD

**Issue by zhaogangang** [potamides/pantran.nvim#10]
sometimes, we prefer to use pantran translate text, if when open pantran, auto enter insert mode not normal mode.
if i want translate buffer's text, i prefer visualize text and :Pantran is work better

**Comment by doongjohn** [comment]
this worked for me
```lua
vim.api.nvim_set_keymap('n', 'your mapping', '<cmd>Pantran<cr>i', { noremap = false })
```

**Comment by zhaogangang** [comment]
ohhhh, it's usefull for me, thank you
