### ISSUE TITLE
Possible typo in README

### ISSUE THREAD

**Issue by fmbarina** [potamides/pantran.nvim#12]
In README.md

> similar to how most of the various machine translation web **font**-ends work.

Maybe you meant:

> similar to how most of the various machine translation web **front**-ends work.

Thought I should point this out.

I could've made a PR, but I'm not sure that it's a mistake. 
And even if I was, I'd feel bad adding myself to the contributors simply because of a typo.

Thanks for making this plugin.

**Comment by potamides** [comment]
Oh yeah, this is indeed a typo! Thank you for helping to make this plugin better.
