### ISSUE TITLE
Setting default_source and default_target does not work.

### ISSUE THREAD

**Issue by atishdhu** [potamides/pantran.nvim#17]
## My config
I want to set default engine to `google` and its `default_source` to `english` and `default_target` to `french`. I have the following config in `plugins.lua`:
```lua
{
    "potamides/pantran.nvim",
    event = "VimEnter",
    config = function()
      require("pantran").setup({
        default_engine = "google",
        engines = {
          google = {
            default_source = "auto",
            default_target = "fr"
          },
        },
      })
    end
  },
```

I also tried with:
```lua
{
    "potamides/pantran.nvim",
    event = "VimEnter",
    config = function()
      require("pantran").setup({
        default_engine = "google",
        engines = {
          google = {
            config = {
              default_source = "auto",
              default_target = "fr"
            }
          },
        },
      })
    end
  },
```
## Expectation
Source is `english` and target is `french` when i execute `:Pantran`.

## Actual Result
Source is `auto` and target is `english` when i execute `:Pantran`.

**Comment by potamides** [comment]
You are probably using the fallback endpoint, so you need to use the following [configuration keys](https://github.com/potamides/pantran.nvim/blob/ab49d88ca7a308d404fbd52844aeddb62a9befb8/doc/pantran.txt#L357-L362). On a side note, this seems to be a reoccurring point of confusion, so this should be documented better.

**Comment by atishdhu** [comment]
I updated the config and it works now, thank you.
```lua
{
    "potamides/pantran.nvim",
    event = "VimEnter",
    config = function()
      require("pantran").setup({
        default_engine = "google",
        engines = {
          google = {
            fallback = {
              default_source = "auto",
              default_target = "fr"
            }
          },
        },
      })
    end
  },
```
