### ISSUE TITLE
`pantran.motion_translate` doesn't work

### ISSUE THREAD

**Issue by TornaxO7** [potamides/pantran.nvim#3]
Hi! I have the following keybindings at the moment:
```lua
local pantran = require("pantran")

local opts = {noremap = true, silent = true}
vim.keymap.set("n", "mt", pantran.motion_translate, ops)
vim.keymap.set("x", "mt", pantran.motion_translate, ops)
```

When I do `nvim /tmp/test.txt` and press `mt` nothing happens.
But if I use
```lua
local pantran = require("pantran")

local opts = {noremap = true, silent = true}
-- vim.keymap.set("n", "mt", pantran.motion_translate, ops)
-- vim.keymap.set("x", "mt", pantran.motion_translate, ops)
vim.keymap.set("n", "mt", function() vim.api.nvim_command("Pantran") end, ops)
vim.keymap.set("x", "mt", function() vim.api.nvim_command("Pantran") end, ops)
```
instead, pressing `mt` works in normal mode but not in visual mode.

**Comment by potamides** [comment]
Hi! You need to use an `<expr>` mapping or it won't work. Also, `ops` in the argument list is probably a typo and should be `opts`. The following should work:
```lua
local pantran = require("pantran")

local opts = {noremap = true, silent = true, expr = true}
vim.keymap.set("n", "mt", pantran.motion_translate, opts)
vim.keymap.set("x", "mt", pantran.motion_translate, opts)
```

**Comment by potamides** [comment]
Oh, I just realized that the example mappings in the README do not contain the `<expr>` flag. Thanks for bringing this to my attention!

**Comment by TornaxO7** [comment]
>  Also, ops in the argument list is probably a typo and should be opts.

Ah yes, you're right!

>  You need to use an <expr> mapping or it won't work.

Oh ok

> Oh, I just realized that the example mappings in the README do not contain the <expr> flag. Thanks for bringing this to my attention!

Good that it's added now ^^

**Comment by TornaxO7** [comment]
Hm.... Now I'm getting another issue. This is my setup call:
```lua
pantran.setup({
    default_engine = "google",
    engines = {
        google = {
            default_source = "en",
            default_target = "de",
        },
    }
})
```
now if I execute my keybinding, the ui opens as follows:
![image](https://user-images.githubusercontent.com/50843046/188746824-a246b646-0eb9-40da-9941-37a36b63360b.png)

I expected to have `de` as the target language. Am I doing something wrong?

**Comment by potamides** [comment]
Ah yes, that might be a bit tricky. Did you set up a Bearer token or API key for Google somewhere? If not Pantran uses a fallback API. Since the options and language identifiers can be different for that configuration is done in the `fallback` table. So your config should look like this:
```lua
pantran.setup({
    default_engine = "google",
    engines = {
        google = {
            fallback = {
                default_source = "en",
                default_target = "de",
            }
        }
    }
})
```

**Comment by TornaxO7** [comment]
Yay, it's fully working now as expected! Thank you :)

**Comment by sahinakkaya** [comment]
> Ah yes, that might be a bit tricky. Did you set up a Bearer token or API key for Google somewhere? If not Pantran uses a fallback API. Since the options and language identifiers can be different for that configuration is done in the `fallback` table. So your config should look like this:
> 
> ```lua
> pantran.setup({
>     default_engine = "google",
>     engines = {
>         google = {
>             fallback = {
>                 default_source = "en",
>                 default_target = "de",
>             }
>         }
>     }
> })
> ```

I think this should be written somewhere in the README.
