### ISSUE TITLE
Engine configurations do not apply.

### ISSUE THREAD

**Issue by NikolaM-Dev** [potamides/pantran.nvim#4]
## Description

Using the following configuration and making several attempts with different `default_target` and `default_source` settings

```lua
local status_ok, pantran = pcall(require, 'pantran')
if not status_ok then
	return
end

pantran.setup({
	default_engine = 'google',
	engines = {
		google = {
			default_target = 'es',
		},
	},
})
```

I always get the same result
![image](https://user-images.githubusercontent.com/62358156/192189244-f9b004fc-1db2-4e54-95dc-180cc72c2942.png)

`default_targe = 'en'` & `default_source = 'auto'`

**Comment by potamides** [comment]
Please try [#3](https://github.com/potamides/pantran.nvim/issues/3#issuecomment-1238959050) and see if it works. Btw, is there a particular reason you use pcall for requiring pantran?

**Comment by NikolaM-Dev** [comment]
> Please try [#3](https://github.com/potamides/pantran.nvim/issues/3#issuecomment-1238959050) and see if it works. Btw, is there a particular reason you use pcall for requiring pantran?

This solves my problem thank you very much.
The need for pcall is to have a neovim setup where all errors are handled.
