### ISSUE TITLE
`:'<,'>Pantran` can only translate the whole line

### ISSUE THREAD

**Issue by Chilly-Blaze** [potamides/pantran.nvim#8]
I want to be able to translate what is selected in visual mode, so I try`:'<,'>Pantran`but it doesn't work.Pantran always translates the whole line word.
What should I do?

**Comment by potamides** [comment]
Commands in Vim are line-based, so even if your selection is within a line, the command still takes the whole line into account (this also holds for `:substitute`, for example). To get your desired behavior, you can use the recommended [keybindings](https://github.com/potamides/pantran.nvim#quickstart) in the README. They are based on Vims [map-operator](https://neovim.io/doc/user/map.html#%3Amap-operator) feature, which supports what you want to do.

**Comment by Chilly-Blaze** [comment]
thx.I will try to solve it.

**Comment by doongjohn** [comment]
I found an alternative solution:
```lua
vim.keymap.set('v', 'your mapping', 'y<cmd>Pantran<cr>p')
```
btw thank you for creating this plugin! 👍
